futi:
  code-validity-time: 600000
spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/futi?serverTimezone=UTC&autoReconnect=true
    #username: root
    #password: ----
    url: jdbc:mysql://dev-futi.copnmzh6ijl2.us-west-2.rds.amazonaws.com:3306/futi?serverTimezone=UTC&autoReconnect=true
    username: admin
    password: winmorefuti
    driver-class-name: com.mysql.cj.jdbc.Driver
    validation-query: SET time_zone = America/Bogota
    dbcp2:
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1
      max-total: 10
      initial-size: 5
      validation-query-timeout: 60
oauth:
  datasource:
    #    url: jdbc:mysql://localhost:3306/futi_oauth?serverTimezone=UTC&autoReconnect=true
    #username: root
    #password: ----
    url: jdbc:mysql://dev-futi.copnmzh6ijl2.us-west-2.rds.amazonaws.com:3306/futi_oauth?serverTimezone=UTC&autoReconnect=true
    username: admin
    password: winmorefuti
    driver-class-name: com.mysql.cj.jdbc.Driver
    validation-query: SET time_zone = America/Bogota
    dbcp2:
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1
      max-total: 10
      initial-size: 5
      validation-query-timeout: 60
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8069
  servlet:
    context-path: /futi
    session:
      timeout: 1800s
